/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Login` | `/Login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignIn` | `/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/blocked-users` | `/blocked-users`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/editProfile` | `/editProfile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/followers` | `/followers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/following` | `/following`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/help` | `/help`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/setting` | `/setting`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/Login` | `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/SignIn` | `/SignIn`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/blocked-users` | `/blocked-users`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/editProfile` | `/editProfile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/followers` | `/followers`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/following` | `/following`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/help` | `/help`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/setting` | `/setting`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/Login${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/SignIn${`?${string}` | `#${string}` | ''}` | `/SignIn${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/blocked-users${`?${string}` | `#${string}` | ''}` | `/blocked-users${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/editProfile${`?${string}` | `#${string}` | ''}` | `/editProfile${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/followers${`?${string}` | `#${string}` | ''}` | `/followers${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/following${`?${string}` | `#${string}` | ''}` | `/following${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/help${`?${string}` | `#${string}` | ''}` | `/help${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/setting${`?${string}` | `#${string}` | ''}` | `/setting${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/notifications${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Login` | `/Login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignIn` | `/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/blocked-users` | `/blocked-users`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/editProfile` | `/editProfile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/followers` | `/followers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/following` | `/following`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/help` | `/help`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/setting` | `/setting`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notifications` | `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
